// src/components/editor/Keyboard.tsx
import {useState, useEffect, useRef} from 'react'
import LeftChevron from '@/components/svg/LeftChevron'
import RightChevron from '@/components/svg/RightChevron'
import Delete from '@/components/svg/Delete'
import Brackets from '@/components/svg/Brackets'

type Letter = Algo.SingleFingerSide | Algo.FullHandSide
interface KeyboardProps {
  show: boolean,

  side: Letter | '',
  prime: boolean,
  double: boolean,

  onLetter: (letter: Letter) => void,
  onNext: () => void,
  onPrevious: () => void,
  onInsertLeft: () => void,
  onInsertRight: () => void,
  onDelete: () => void,
  onGroup: () => void,
  onPrime: () => void
  onDouble: () => void,

  disableLetters: boolean,
  disablePrimeDouble: boolean,

  disableNext: boolean,
  disablePrevious: boolean,
  disableDelete: boolean,
  disableGroup: boolean,
  disableInsertLeft: boolean,
  disableInsertRight: boolean
}

const letters: Letter[] = [
  'R', 'L', 'U', 'F', 'D', 'B',
  'r', 'l', 'u', 'f', 'd', 'b',
  'M', 'S', 'E', 'x', 'y', 'z'
]

const togglableKey = (on: boolean) => {
  let cls = 'h-auto p-0 shadow-md relative before:absolute enabled:before:inset-0 hover:before:bg-white/10 focus:before:bg-white/20 outline-none disabled:text-font/40 dark:disabled:text-font-dark/40'
  if (on)
    cls += ' bg-primary'
  else
    cls += ' bg-secondary dark:bg-secondary-dark'
  return cls
}
const insertKey = `${togglableKey(false)} flex items-center justify-center`
const actionKey = `${insertKey} keyboard-h:col-span-2 keyboard-w:col-span-2`

const Keyboard = ({
  show,
  side, prime, double,
  onLetter, onDouble, onPrime,
  onPrevious, onNext, onDelete, onGroup, onInsertLeft, onInsertRight,
  disableLetters, disablePrimeDouble,
  disableDelete, disableGroup, disableInsertLeft, disableInsertRight, disableNext, disablePrevious
}: KeyboardProps) => {
  const [render, setRender] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (show && !render)
      return setRender(true)
    if (!render)
      return
    const div = ref.current!
    div.style.transform = 'translateY(110%)'
  }, [show])

  useEffect(() => {
    if (!render) 
      return
    const div = ref.current!
    div.getBoundingClientRect()
    div.style.transform = 'translateY(0%)'
  }, [render])

  const handleTransitionEnd = () => {
    if (show)
      return
    setRender(false)
  }

  return <>{render &&
    <div ref={ref} onTransitionEnd={handleTransitionEnd} className="transition-transform translate-y-[110%] shadow-[0_-.1rem_2rem_rgba(0,0,0,.2)] fixed bottom-0 left-0 right-0 flex justify-center text-lg z-20 bg-surface dark:bg-surface-dark">
      <div className="keyboard-h:aspect-[12/4.5] keyboard-w:aspect-[12/4.5] keyboard-h:grid-cols-[repeat(12,1fr)] keyboard-w:grid-cols-[repeat(12,1fr)] max-w-sm w-full grid grid-cols-[repeat(6,1fr)] aspect-[6/5] auto-rows-[1fr] px-[6px] py-1 gap-1">
        <button className={`${togglableKey(prime)} col-span-3`}  onClick={onPrime}  disabled={disablePrimeDouble}>Prime</button>
        <button className={`${togglableKey(double)} col-span-3`} onClick={onDouble} disabled={disablePrimeDouble}>Double</button>

        {letters.map(letter => <button key={letter} className={togglableKey(side === letter)} onClick={() => onLetter(letter)} disabled={disableLetters}>{letter}</button>)}

        <button className={actionKey} onClick={onPrevious} disabled={disablePrevious}>
          <LeftChevron height="2em"/>
        </button>
        <button className={actionKey} onClick={onNext} disabled={disableNext}>
          <RightChevron height="2em"/>
        </button>
        <button className={actionKey} onClick={onDelete} disabled={disableDelete}>
          <Delete height="1.5em"/>
        </button>
        <button className={actionKey} onClick={onGroup} disabled={disableGroup}>
          <Brackets height="1.5em"/>
        </button>
        <div className="keyboard-h:col-span-4 keyboard-w:col-span-4 grid grid-cols-[50%_50%] col-span-2">
          <button className={`${insertKey} col-start-1 col-end-2 row-start-1 pr-3`} onClick={onInsertLeft} disabled={disableInsertLeft}>
            <LeftChevron height="2em"/>
          </button>
          <button className={`${insertKey} col-start-2 col-end-3 row-start-1 pl-3`} onClick={onInsertRight} disabled={disableInsertRight}>
            <RightChevron height="2em"/>
          </button>
          <div className="row-start-1 col-start-1 col-end-3 z-10 flex items-center justify-center pointer-events-none translate-y-[-5%]">Insert</div>
        </div>
      </div>
    </div>
  }</>
}

export default Keyboard

// src/lib/Keyboard.svelte
<script lang="ts">
    import Ripple from '@smui/ripple'
    import {Icon} from '@smui/common'
    import {Svg} from '@smui/common/elements'
    import {mdiChevronLeft, mdiChevronRight, mdiDelete, mdiCodeBrackets} from '@mdi/js'

    import type {TransitionConfig} from 'svelte/transition'
    import {cubicOut} from 'svelte/easing'

    import {createEventDispatcher} from 'svelte'

    export let double: boolean
    export let prime: boolean
    export let side: SingleFingerSide | FullHandSide | '' = ''

    export let disablePrevious = false
    export let disableDelete = false
    export let disableGroup = false
    export let disableInsertLeft = false
    export let disableInsertRight = false

    const fly = (node: Element, {}): TransitionConfig => {
        return {
            duration: 300,
            easing: cubicOut,
            css: (t, u) => {
                return `transform: translateY(${u * 110}%);`
            }
        }
    }

    const letters: Array<SingleFingerSide | FullHandSide> = [
        'R', 'L', 'U', 'F', 'D', 'B',
        'r', 'l', 'u', 'f', 'd', 'b',
        'M', 'S', 'E', 'x', 'y', 'z'
    ]

    const togglePrime = () => prime = !prime
    const toggleDouble = () => double = !double
    const setSide = (s: SingleFingerSide | FullHandSide) => () => {
        side = s
        dispatch('letter', s)
    }

    const dispatch = createEventDispatcher()

    const nextHandler = () => dispatch('next')
    const previousHandler = () => dispatch('previous')
    const insertLeftHandler = () => dispatch('insertleft')
    const insertRightHandler = () => dispatch('insertright')
    const delHandler = () => dispatch('delete')
    const groupHandler = () => dispatch('group')

    const toggleKey = "key mdc-button mdc-button--raised"
    const actionKey = `${toggleKey} smui-button--color-secondary`
</script>

<div class="keyboard" transition:fly>
    <div class="grid">
        <button use:Ripple={{surface: true}} class="{toggleKey} long" class:smui-button--color-secondary={!prime} on:click={togglePrime}>Prime</button>
        <button use:Ripple={{surface: true}} class="{toggleKey} long" class:smui-button--color-secondary={!double} on:click={toggleDouble}>Double</button>

        {#each letters as letter}
            <button use:Ripple={{surface: true}} class="{toggleKey}" class:smui-button--color-secondary={side !== letter} on:click={setSide(letter)}>{letter}</button>
        {/each}

        <button use:Ripple={{surface: true}} disabled={disablePrevious} class="{actionKey}" on:click={previousHandler}>
            <Icon component={Svg} viewBox="0 0 24 24">
                <path fill="currentColor" d={mdiChevronLeft}/>
            </Icon>
        </button>
        <button use:Ripple={{surface: true}} class="{actionKey}" on:click={nextHandler}>
            <Icon component={Svg} viewBox="0 0 24 24">
                <path fill="currentColor" d={mdiChevronRight}/>
            </Icon>
        </button>
        <button use:Ripple={{surface: true}} disabled={disableDelete} class="{actionKey}" on:click={delHandler}>
            <Icon component={Svg} viewBox="0 0 24 24">
                <path fill="currentColor" d={mdiDelete}/>
            </Icon>
        </button>
        <button use:Ripple={{surface: true}} disabled={disableGroup} class="{actionKey}" on:click={groupHandler}>
            <Icon component={Svg} viewBox="0 0 24 24">
                <path fill="currentColor" d={mdiCodeBrackets}/>
            </Icon>
        </button>
        <div class="insert smui-button__group">
            <button use:Ripple={{surface: true}} disabled={disableInsertLeft} class="{actionKey} insert-left" on:click={insertLeftHandler}>
                <Icon component={Svg} viewBox="0 0 24 24">
                    <path fill="currentColor" d={mdiChevronLeft}/>
                </Icon>
            </button>
            <div class="insert-text">Insert</div>
            <button use:Ripple={{surface: true}} disabled={disableInsertRight} class="{actionKey} insert-right" on:click={insertRightHandler}>
                <Icon component={Svg} viewBox="0 0 24 24">
                    <path fill="currentColor" d={mdiChevronRight}/>
                </Icon>
            </button>
        </div>
    </div>
</div>


<style>
    .keyboard {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        display: flex;
        justify-content: center;
        font-size: 1.2rem;
        z-index: 10;
    }
    .grid {
        width: min(25rem, 100%);
        display: grid;
        grid-template-columns: repeat(6, 1fr);
        gap: .3rem;
        background-color: var(--clr-surface);
        padding: 4px;
        padding-bottom: 0;
        border-radius: 4px;
    }
    @media (max-width: 315px) {
        .grid {
            gap: .1rem;
        }
    }
    .key {
        aspect-ratio: 1 / 1;
        height: auto;
        min-width: auto;
        padding: 0;
    }
    .long {
        aspect-ratio: 3 / 1;
        grid-column: span 3;
    }
    .active {
        background-color: darkcyan;
    }
    .insert {
        display: grid;
        grid-template-columns: 50% 50%;
        grid-template-rows: auto;
        grid-column: span 2;
    }
    .insert-left {
        grid-column: 1 / 2;
        grid-row: 1 / 2;
        padding-right: .7em;
    }
    .insert-right {
        grid-column: 2 / 3;
        grid-row: 1 / 2;
        padding-left: .7em;
    }
    .insert-text {
        grid-column: 1 / 3;
        grid-row: 1 / 2;
        z-index: 2;
        display: flex;
        align-items: center;
        justify-content: center;
        pointer-events: none;
        transform: translateY(-5%);
    }
</style>
