// src/lib/Algorithm.svelte
<script lang="ts">
    import {turnToString} from '$lib/algos'

    export let algo: RubicsAlgorithm
</script>

<span class="algo">
    {#each algo.turns as turn}
        {#if 'turns' in turn}
            <span class="turn-group">
                {#each turn.turns as t}
                    <span>{turnToString(t)}</span>
                {/each}
            </span>
        {:else}
            <span>{turnToString(turn)}</span>
        {/if}
    {/each}
</span>

<style>
    .algo {
        display: flex;
        flex-wrap: wrap;
        gap: .2rem;
        text-transform: none;
    }
    .turn-group {
        display: flex;
        gap: .2rem;
    }
    .turn-group::before {
        content: "(";
    }
    .turn-group::after {
        content: ")";
    }
</style>

// src/components/Algorithm.tsx
import {turnToString} from '@/utils/algo'

interface AlgorithmProps {
  algo: Algo.RubicsAlgorithm
}

const Algorithm = ({algo}: AlgorithmProps) => {
  return (
    <span className="flex flex-wrap gap-1">
      {algo.turns.map((turn, index) => {
        const isGroup = 'turns' in turn
        return <span key={index} className={isGroup ? "flex gap-1" : ""}>
          {isGroup
          ? <>
            <span>(</span>
            {turn.turns.map((t, i) => <span key={i}>{turnToString(t)}</span>)}
            <span>)</span>
          </>
          : <span>{turnToString(turn)}</span>}
        </span>
      })}
    </span>
  )
}

export default Algorithm
